# Generated by Django 4.1.3 on 2022-11-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
